# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fotisnikolidais/Desktop/project/Computational_Geometry

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fotisnikolidais/Desktop/project/Computational_Geometry

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fotisnikolidais/Desktop/project/Computational_Geometry/CMakeFiles /home/fotisnikolidais/Desktop/project/Computational_Geometry//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fotisnikolidais/Desktop/project/Computational_Geometry/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

hull.o: hull.cc.o
.PHONY : hull.o

# target to build an object file
hull.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hull.cc.o
.PHONY : hull.cc.o

hull.i: hull.cc.i
.PHONY : hull.i

# target to preprocess a source file
hull.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hull.cc.i
.PHONY : hull.cc.i

hull.s: hull.cc.s
.PHONY : hull.s

# target to generate assembly for a file
hull.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hull.cc.s
.PHONY : hull.cc.s

incremental.o: incremental.cpp.o
.PHONY : incremental.o

# target to build an object file
incremental.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.o
.PHONY : incremental.cpp.o

incremental.i: incremental.cpp.i
.PHONY : incremental.i

# target to preprocess a source file
incremental.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.i
.PHONY : incremental.cpp.i

incremental.s: incremental.cpp.s
.PHONY : incremental.s

# target to generate assembly for a file
incremental.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.s
.PHONY : incremental.cpp.s

kd_tree.o: kd_tree.cpp.o
.PHONY : kd_tree.o

# target to build an object file
kd_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/kd_tree.cpp.o
.PHONY : kd_tree.cpp.o

kd_tree.i: kd_tree.cpp.i
.PHONY : kd_tree.i

# target to preprocess a source file
kd_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/kd_tree.cpp.i
.PHONY : kd_tree.cpp.i

kd_tree.s: kd_tree.cpp.s
.PHONY : kd_tree.s

# target to generate assembly for a file
kd_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/kd_tree.cpp.s
.PHONY : kd_tree.cpp.s

localsearch.o: localsearch.cpp.o
.PHONY : localsearch.o

# target to build an object file
localsearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localsearch.cpp.o
.PHONY : localsearch.cpp.o

localsearch.i: localsearch.cpp.i
.PHONY : localsearch.i

# target to preprocess a source file
localsearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localsearch.cpp.i
.PHONY : localsearch.cpp.i

localsearch.s: localsearch.cpp.s
.PHONY : localsearch.s

# target to generate assembly for a file
localsearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localsearch.cpp.s
.PHONY : localsearch.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

polygon.o: polygon.cc.o
.PHONY : polygon.o

# target to build an object file
polygon.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/polygon.cc.o
.PHONY : polygon.cc.o

polygon.i: polygon.cc.i
.PHONY : polygon.i

# target to preprocess a source file
polygon.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/polygon.cc.i
.PHONY : polygon.cc.i

polygon.s: polygon.cc.s
.PHONY : polygon.s

# target to generate assembly for a file
polygon.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/polygon.cc.s
.PHONY : polygon.cc.s

simulated_annealing.o: simulated_annealing.cpp.o
.PHONY : simulated_annealing.o

# target to build an object file
simulated_annealing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulated_annealing.cpp.o
.PHONY : simulated_annealing.cpp.o

simulated_annealing.i: simulated_annealing.cpp.i
.PHONY : simulated_annealing.i

# target to preprocess a source file
simulated_annealing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulated_annealing.cpp.i
.PHONY : simulated_annealing.cpp.i

simulated_annealing.s: simulated_annealing.cpp.s
.PHONY : simulated_annealing.s

# target to generate assembly for a file
simulated_annealing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulated_annealing.cpp.s
.PHONY : simulated_annealing.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... hull.o"
	@echo "... hull.i"
	@echo "... hull.s"
	@echo "... incremental.o"
	@echo "... incremental.i"
	@echo "... incremental.s"
	@echo "... kd_tree.o"
	@echo "... kd_tree.i"
	@echo "... kd_tree.s"
	@echo "... localsearch.o"
	@echo "... localsearch.i"
	@echo "... localsearch.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... polygon.o"
	@echo "... polygon.i"
	@echo "... polygon.s"
	@echo "... simulated_annealing.o"
	@echo "... simulated_annealing.i"
	@echo "... simulated_annealing.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

